# A linha 'version' não é mais necessária nas versões recentes do Docker Compose
services:
  api:
    build: .
    container_name: personal_trainer_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres_db:5432/personal_trainer_db
      - PGHOST=postgres_db
    depends_on:
      - postgres_db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=personal_trainer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: