version: '3.8'

services:
  api:
    build: .
    container_name: personal_trainer_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    # ✅ ADICIONE ESTA SEÇÃO
    environment:
      # O hostname aqui é o NOME DO SERVIÇO do banco de dados, não localhost!
      - DATABASE_URL=postgresql://postgres:postgres@postgres_db:5432/personal_trainer_db
    # ✅ ADICIONE ESTA LINHA
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=personal_trainer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: